"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Download, KeyRound, Plus, ShieldCheck, UserCheck, UserX } from "lucide-react";
import SectionHeader from "@/components/ui/SectionHeader";
import { requestJson } from "@/lib/api";

type Page<T> = { data: T[]; nextCursor: string | null; total: number };
type User = { id:string; name:string; email:string; role:"ADMIN"|"READER"; isSuspended:boolean; mustChangePassword:boolean; createdAt:string; _count:{readingHistory:number;submissions:number} };
type History = { id:string; pageIndex:number; completed:boolean; updatedAt:string; user:{id:string;name:string;email:string}; comic:{title:string;slug:string}; chapter:{number:number;title:string} };

export default function UsersPage() {
  const qc=useQueryClient(); const [tab,setTab]=useState<"users"|"history">("users"); const [q,setQ]=useState(""); const [role,setRole]=useState("ALL"); const [status,setStatus]=useState("ALL"); const [cursor,setCursor]=useState<string>(); const [showCreate,setShowCreate]=useState(false); const [notice,setNotice]=useState("");
  const users=useQuery({queryKey:["admin","users",q,role,status,cursor],enabled:tab==="users",queryFn:()=>requestJson<Page<User>>(`/api/admin/users?q=${encodeURIComponent(q)}&role=${role}&status=${status}${cursor?`&cursor=${cursor}`:""}`)});
  const history=useQuery({queryKey:["admin","history",q,cursor],enabled:tab==="history",queryFn:()=>requestJson<Page<History>>(`/api/admin/history?q=${encodeURIComponent(q)}${cursor?`&cursor=${cursor}`:""}`)});
  const patch=useMutation({mutationFn:({id,...body}:{id:string;role?:string;isSuspended?:boolean;temporaryPassword?:string})=>requestJson(`/api/admin/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","users"]});setNotice(current=>current.startsWith("New temporary password:")?current:"Account updated.")},onError:(e:Error)=>setNotice(e.message)});
  const create=useMutation({mutationFn:(body:Record<string,string>)=>requestJson("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin","users"]});setShowCreate(false);setNotice("User created. They must change their temporary password at first login.")},onError:(e:Error)=>setNotice(e.message)});
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);create.mutate(Object.fromEntries(f.entries()) as Record<string,string>)}
  const active=tab==="users"?users.data:history.data; const loading=tab==="users"?users.isLoading:history.isLoading; const failed=tab==="users"?users.isError:history.isError;
  return <div><SectionHeader title="Users & Reading History" subtitle="Manage accounts and understand reader activity at scale"/>
    <div className="admin-tabs"><button className={tab==="users"?"active":""} onClick={()=>{setTab("users");setCursor(undefined)}}>Users</button><button className={tab==="history"?"active":""} onClick={()=>{setTab("history");setCursor(undefined)}}>Reading History</button></div>
    {notice&&<p className="status" role="status" style={{marginBottom:14}}>{notice}</p>}
    {showCreate&&<form className="admin-form" onSubmit={submit}><input name="name" minLength={2} required placeholder="Full name"/><input name="email" type="email" required placeholder="Email address"/><input name="password" type="password" minLength={8} required placeholder="Temporary password"/><select name="role"><option value="READER">Reader</option><option value="ADMIN">Admin</option></select><button className="admin-action" disabled={create.isPending} type="submit"><Plus size={16}/>{create.isPending?"Creating…":"Create account"}</button><button className="admin-action" type="button" onClick={()=>setShowCreate(false)}>Cancel</button></form>}
    <div className="admin-tools"><input value={q} onChange={e=>{setQ(e.target.value);setCursor(undefined)}} placeholder={tab==="users"?"Search name or email…":"Search reader or comic…"}/>{tab==="users"&&<><select value={role} onChange={e=>{setRole(e.target.value);setCursor(undefined)}}><option>ALL</option><option>READER</option><option>ADMIN</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setCursor(undefined)}}><option>ALL</option><option>ACTIVE</option><option>SUSPENDED</option></select><button className="admin-action" onClick={()=>setShowCreate(true)}><Plus size={15}/>Create user</button></>}<a href={tab==="users"?`/api/admin/users?q=${encodeURIComponent(q)}&role=${role}&status=${status}&format=csv`:`/api/admin/history?q=${encodeURIComponent(q)}&format=csv`}><Download size={15}/>Export CSV</a></div>
    {loading?<p>Loading…</p>:failed?<p className="error">Unable to load data.</p>:!active?.data.length?<p className="admin-empty">No records found.</p>:tab==="users"?<div className="admin-list">{users.data!.data.map(u=><article key={u.id}><div><span className="status">{u.role} · {u.isSuspended?"SUSPENDED":"ACTIVE"}</span><h3>{u.name}</h3><p>{u.email}</p><small>{u._count.readingHistory} reading entries · {u._count.submissions} submissions{u.mustChangePassword?" · Password change required":""}</small></div><div className="row-actions"><button onClick={()=>patch.mutate({id:u.id,role:u.role==="ADMIN"?"READER":"ADMIN"})}><ShieldCheck size={15}/>{u.role==="ADMIN"?"Make reader":"Make admin"}</button><button onClick={()=>patch.mutate({id:u.id,isSuspended:!u.isSuspended})}>{u.isSuspended?<UserCheck size={15}/>:<UserX size={15}/>} {u.isSuspended?"Reactivate":"Suspend"}</button><button onClick={()=>{const temporaryPassword=crypto.randomUUID().replaceAll("-","").slice(0,12);setNotice(`New temporary password: ${temporaryPassword}`);patch.mutate({id:u.id,temporaryPassword})}}><KeyRound size={15}/>Reset password</button></div></article>)}</div>:<div className="admin-list">{history.data!.data.map(h=><article key={h.id}><div><span className="status"><BookOpen size={12}/> {h.completed?"COMPLETED":"IN PROGRESS"}</span><h3>{h.comic.title}</h3><p>{h.user.name} · {h.user.email}</p><small>Chapter {h.chapter.number}: {h.chapter.title} · Page {h.pageIndex+1} · {new Date(h.updatedAt).toLocaleString()}</small></div></article>)}</div>}
    <div className="pager"><span>{active?.total??0} records</span>{active?.nextCursor&&<button onClick={()=>setCursor(active.nextCursor!)}>Next page →</button>}</div>
  </div>
}
