"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter, useSearchParams } from "next/navigation";
import Button from "@/components/ui/Button";
import { getSession, queryKeys, requestJson } from "@/lib/api";
import PasswordInput from "@/components/ui/PasswordInput";
import LoadingState from "@/components/ui/LoadingState";
import { BookCheck, BookOpen, Clock3, Heart, History, Home, Library, LogOut, Settings, UserRound } from "lucide-react";

type History = { id: string; pageIndex: number; completed: boolean; updatedAt: string; chapter: { number: number; title: string }; comic: { id: string; slug: string; title: string; coverImage: string } };
type Submission = { id: string; title: string; status: string; reviewNote?: string; comic?: { slug: string; title: string } | null };
type Profile = { name: string; email: string; avatarUrl?: string; bio?: string };
type Liked = { comic: { id:string; slug:string; title:string; coverImage:string; author:string } };
const input = { width: "100%", padding: 12, borderRadius: "var(--radius-md)", border: "1px solid var(--color-border)", background: "var(--color-bg-elevated)", color: "var(--color-text-primary)" };

export default function ReaderDashboard() {
  const router = useRouter(); const qc = useQueryClient();
  const searchParams = useSearchParams();
  const [tab, setTab] = useState(() => searchParams.get("tab") === "my-comics" ? "my comics" : "overview"); const [notice, setNotice] = useState("");
  const { data: session, isLoading: checking } = useQuery({ queryKey: queryKeys.session, queryFn: getSession });
  const { data: profile } = useQuery({ queryKey: queryKeys.profile, queryFn: () => requestJson<Profile>("/api/reader/profile"), enabled: session?.role === "READER" });
  const { data: history = [], isLoading: historyLoading, isError: historyError } = useQuery({ queryKey: queryKeys.history, queryFn: () => requestJson<History[]>("/api/reader/history"), enabled: session?.role === "READER" });
  const { data: submissions = [], isLoading: submissionsLoading } = useQuery({ queryKey: queryKeys.submissions, queryFn: () => requestJson<Submission[]>("/api/reader/submissions"), enabled: session?.role === "READER" });
  const { data: liked = [] } = useQuery({ queryKey: ["reader","likes"], queryFn: () => requestJson<Liked[]>("/api/reader/likes"), enabled: session?.role === "READER" });
  const [readerTheme,setReaderTheme]=useState(()=>typeof window==="undefined"?"default":window.localStorage.getItem("mycomic:reader-theme")||"default");
  const chooseTheme=(theme:string)=>{setReaderTheme(theme);window.localStorage.setItem("mycomic:reader-theme",theme);if(theme==="default")document.documentElement.removeAttribute("data-reader-theme");else document.documentElement.setAttribute("data-reader-theme",theme)};
  const [profileForm, setProfileForm] = useState({ name: "", avatarUrl: "", bio: "", currentPassword: "", newPassword: "" });
  const [submission, setSubmission] = useState({ title: "", description: "", storyContent: "", coverUrl: "", contentUrl: "" });
  const saveProfile = useMutation({ mutationFn: (body: object) => requestJson("/api/reader/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), onSuccess: () => { qc.invalidateQueries({ queryKey: queryKeys.profile }); setNotice("Profile saved"); }, onError: () => setNotice("Could not save profile") });
  const submitComic = useMutation({ mutationFn: () => requestJson("/api/reader/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(submission) }), onSuccess: () => { qc.invalidateQueries({ queryKey: queryKeys.submissions }); setSubmission({ title: "", description: "", storyContent: "", coverUrl: "", contentUrl: "" }); setNotice("Story submitted for review"); }, onError: () => setNotice("Submission failed. Add a title, description, and story.") });
  const upload = useMutation({ mutationFn: async ({ file, field }: { file: File; field: "coverUrl" | "contentUrl" }) => { const body = new FormData(); body.append("file", file); body.append("folder", "submissions"); const result = await requestJson<{ url: string }>("/api/uploads", { method: "POST", body }); return { field, url: result.url }; }, onSuccess: ({ field, url }) => setSubmission((current) => ({ ...current, [field]: url })), onError: () => setNotice("File upload failed") });
  const logout = useMutation({ mutationFn: () => requestJson("/api/auth/logout", { method: "POST" }), onSuccess: () => { qc.clear(); router.replace("/signin"); } });
  const unauthorized = !checking && session?.role !== "READER";
  useEffect(() => { if (unauthorized) router.replace("/signin"); }, [unauthorized, router]);
  if (unauthorized) return <LoadingState label="Redirecting securely" variant="page"/>;
  if (checking) return <LoadingState label="Preparing your dashboard" variant="page"/>;
  const ongoing = history.filter((item) => !item.completed);
  const completed = history.filter((item) => item.completed);
  const tabs = ["overview", "profile", "history", "ongoing", "completed", "liked", "my comics", "settings"];
  const tabIcons = [Home, UserRound, History, Clock3, BookCheck, Heart, Library, Settings];
  const historyList = (items: History[]) => historyLoading ? <p>Loading history…</p> : historyError ? <p style={{ color: "var(--color-error)" }}>Could not load history.</p> : items.length === 0 ? <p style={{ color: "var(--color-text-secondary)" }}>No reading activity yet.</p> : <div style={{ display: "grid", gap: 10 }}>{items.map((item) => <div key={item.id} style={{ padding: 16, border: "1px solid var(--color-border)", borderRadius: "var(--radius-lg)", display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><div><strong>{item.comic.title}</strong><p style={{ color: "var(--color-text-secondary)" }}>Chapter {item.chapter.number}: {item.chapter.title} · Page {item.pageIndex + 1}</p></div><Button size="sm" href={`/comic/${item.comic.slug}/read/${item.chapter.number}?page=${item.pageIndex}`}>Continue</Button></div>)}</div>;
  return <main className="reader-dashboard"><aside className="reader-sidebar"><div className="reader-user"><div className="reader-avatar">{(profile?.name ?? session?.name ?? "R").charAt(0).toUpperCase()}</div><div><strong>{profile?.name ?? session?.name}</strong><span>{profile?.email ?? session?.email}</span></div></div><nav>{tabs.map((name, index) => {const Icon=tabIcons[index];return <button key={name} onClick={() => setTab(name)} className={tab === name ? "active" : ""}><span className="nav-icon"><Icon size={16}/></span><span style={{ textTransform: "capitalize" }}>{name}</span></button>})}<button className="logout-tab" onClick={() => logout.mutate()} disabled={logout.isPending}><span className="nav-icon"><LogOut size={16}/></span><span>{logout.isPending ? "Signing out" : "Logout"}</span></button></nav><a className="reader-home" href="/"><BookOpen size={15}/> Back to website</a></aside><div className="reader-main"><header className="reader-header"><div><p>MYCOMIC ACCOUNT</p><h1>{tab === "overview" ? "Reader Dashboard" : tab}</h1><span>Welcome back, {profile?.name ?? session?.name}.</span></div><div className="header-badge">Reader</div></header>
    {notice && <p role="status" className="reader-notice">{notice}</p>}
    {tab === "overview" && <section><div className="reader-stats"><div><span>Series started</span><strong>{history.length}</strong></div><div><span>Currently reading</span><strong>{ongoing.length}</strong></div><div><span>Stories submitted</span><strong>{submissions.length}</strong></div></div><h2>Continue reading</h2><div style={{ marginTop: 16 }}>{historyList(ongoing.slice(0, 3))}</div></section>}
    {tab === "history" && <section><h2>Reading History</h2><div style={{ marginTop: 16 }}>{historyList(history)}</div></section>}
    {tab === "ongoing" && <section><h2>Ongoing Comics</h2><div style={{ marginTop: 16 }}>{historyList(ongoing)}</div></section>}
    {tab === "completed" && <section><h2>Completed Reading</h2><div style={{ marginTop: 16 }}>{historyList(completed)}</div></section>}
    {tab === "liked" && <section><h2>Liked Series</h2><div style={{display:"grid",gap:10,marginTop:16}}>{liked.length?liked.map(item=><div key={item.comic.id} style={{padding:16,border:"1px solid var(--color-border)",borderRadius:"var(--radius-lg)"}}><strong>{item.comic.title}</strong><p style={{color:"var(--color-text-secondary)"}}>By {item.comic.author}</p><Button size="sm" href={`/comic/${item.comic.slug}`}>View series</Button></div>):<p>No liked series yet.</p>}</div></section>}
    {tab === "profile" && <form onSubmit={(e) => { e.preventDefault(); saveProfile.mutate({ name: profileForm.name || profile?.name, avatarUrl: profileForm.avatarUrl || profile?.avatarUrl, bio: profileForm.bio || profile?.bio }); }} style={{ display: "grid", gap: 14, maxWidth: 600 }}><h2>Profile</h2><input style={input} placeholder={profile?.name ?? "Name"} value={profileForm.name} onChange={(e) => setProfileForm({ ...profileForm, name: e.target.value })} /><input style={input} placeholder="Avatar URL" value={profileForm.avatarUrl} onChange={(e) => setProfileForm({ ...profileForm, avatarUrl: e.target.value })} /><textarea style={input} placeholder={profile?.bio ?? "Tell readers about yourself"} rows={5} value={profileForm.bio} onChange={(e) => setProfileForm({ ...profileForm, bio: e.target.value })} /><Button type="submit" disabled={saveProfile.isPending}>Save profile</Button></form>}
    {tab === "settings" && <form onSubmit={(e) => { e.preventDefault(); saveProfile.mutate({ currentPassword: profileForm.currentPassword, newPassword: profileForm.newPassword }); }} style={{ display: "grid", gap: 14, maxWidth: 600 }}><h2>Reader theme</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{["default","midnight","light"].map(theme=><Button key={theme} type="button" variant={readerTheme===theme?"primary":"secondary"} onClick={()=>chooseTheme(theme)}>{theme==="default"?"Back to default":theme}</Button>)}</div><h2 style={{marginTop:14}}>Change password</h2><PasswordInput style={input} placeholder="Current password" value={profileForm.currentPassword} onChange={(e) => setProfileForm({ ...profileForm, currentPassword: e.target.value })} /><PasswordInput style={input} placeholder="New password (8+ characters)" value={profileForm.newPassword} onChange={(e) => setProfileForm({ ...profileForm, newPassword: e.target.value })} /><Button type="submit" disabled={saveProfile.isPending}>Update password</Button></form>}
    {tab === "my comics" && <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,320px),1fr))", gap: 24 }}><form onSubmit={(e) => { e.preventDefault(); submitComic.mutate(); }} style={{ display: "grid", gap: 12 }}><h2>Submit a story</h2><input style={input} placeholder="Title" value={submission.title} onChange={(e) => setSubmission({ ...submission, title: e.target.value })} /><textarea style={input} rows={3} placeholder="Description" value={submission.description} onChange={(e) => setSubmission({ ...submission, description: e.target.value })} /><textarea style={input} rows={8} placeholder="Story content" value={submission.storyContent} onChange={(e) => setSubmission({ ...submission, storyContent: e.target.value })} /><label>Cover image<input style={input} type="file" accept="image/*" onChange={(e) => e.target.files?.[0] && upload.mutate({ file: e.target.files[0], field: "coverUrl" })} /></label><label>Story file<input style={input} type="file" accept=".pdf,.txt,.doc,.docx" onChange={(e) => e.target.files?.[0] && upload.mutate({ file: e.target.files[0], field: "contentUrl" })} /></label><Button type="submit" disabled={submitComic.isPending || upload.isPending}>Send for review</Button></form><div><h2>Your submissions</h2>{submissionsLoading ? <p>Loading…</p> : submissions.length === 0 ? <p>No submissions yet.</p> : submissions.map((item) => <div key={item.id} style={{ padding: 14, border: "1px solid var(--color-border)", borderRadius: "var(--radius-md)", marginTop: 10 }}><strong>{item.title}</strong><p style={{ color: "var(--color-primary)" }}>{item.status}</p>{item.reviewNote && <p>{item.reviewNote}</p>}{item.comic && <a href={`/comic/${item.comic.slug}`}>View published comic</a>}</div>)}</div></section>}
  <style jsx global>{`
    .reader-dashboard{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:calc(100dvh - 64px);background:var(--color-bg-base)}
    .reader-sidebar{position:sticky;top:64px;height:calc(100dvh - 64px);padding:24px 16px;background:var(--color-bg-surface);border-right:1px solid var(--color-border);display:flex;flex-direction:column}
    .reader-user{display:flex;align-items:center;gap:12px;padding:8px 8px 24px;border-bottom:1px solid var(--color-border);margin-bottom:18px;min-width:0}.reader-user>div:last-child{min-width:0}.reader-user strong,.reader-user span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.reader-user span{font-size:12px;color:var(--color-text-tertiary);margin-top:3px}.reader-avatar{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;flex:none;background:linear-gradient(135deg,var(--color-primary),var(--color-tertiary));color:#081006;font-weight:800;font-size:18px}
    .reader-sidebar nav{display:grid;gap:6px}.reader-sidebar nav button{display:flex;align-items:center;gap:12px;width:100%;padding:11px 12px;border-radius:10px;border:1px solid transparent;background:transparent;color:var(--color-text-secondary);font-weight:600;text-align:left}.reader-sidebar nav button.active{color:var(--color-primary);background:rgba(var(--color-primary-rgb),.09);border-color:rgba(var(--color-primary-rgb),.2)}.reader-sidebar nav .logout-tab{color:#f87171}.reader-sidebar nav .logout-tab:hover{background:rgba(239,68,68,.08);border-color:rgba(239,68,68,.2)}.nav-icon{width:26px;height:26px;display:grid;place-items:center;border-radius:7px;background:var(--color-bg-elevated);text-align:center;font-size:15px}.reader-home{margin-top:auto;padding:12px;color:var(--color-text-secondary);text-decoration:none;font-size:13px}
    .reader-main{padding:clamp(22px,4vw,48px);min-width:0;max-width:1500px;width:100%;margin:0 auto}.reader-header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:28px}.reader-header p{font-size:11px;letter-spacing:.14em;color:var(--color-primary);font-weight:800}.reader-header h1{font:700 clamp(1.8rem,3vw,2.6rem)/1.15 var(--font-heading);text-transform:capitalize;margin:5px 0}.reader-header>div>span{color:var(--color-text-secondary)}.header-badge{padding:7px 13px;border:1px solid rgba(var(--color-primary-rgb),.25);border-radius:999px;background:rgba(var(--color-primary-rgb),.08);color:var(--color-primary);font-size:12px;font-weight:700}.reader-notice{padding:12px 15px;border-radius:10px;background:rgba(var(--color-primary-rgb),.08);border:1px solid rgba(var(--color-primary-rgb),.2);color:var(--color-primary);margin-bottom:18px}
    .reader-main>section,.reader-main>form{padding:clamp(18px,3vw,28px);border:1px solid var(--color-border);border-radius:var(--radius-xl);background:var(--color-bg-surface);box-shadow:0 16px 40px rgba(0,0,0,.14)}
    .reader-dashboard{font-family:var(--font-body);font-size:14px;line-height:1.55;letter-spacing:0}.reader-main h2{font-family:var(--font-heading);font-size:clamp(1.15rem,1.8vw,1.35rem);font-weight:700;line-height:1.3;letter-spacing:-.018em;margin:0 0 6px}.reader-main h3{font-family:var(--font-heading);font-size:1rem;font-weight:700;line-height:1.35}.reader-main p,.reader-main a,.reader-main label{font-size:.875rem;line-height:1.55}.reader-main label{display:grid;gap:7px;color:var(--color-text-secondary);font-weight:600}.reader-main input,.reader-main textarea,.reader-main select,.reader-main button{font-family:var(--font-body);font-size:.875rem;line-height:1.45}.reader-main strong{font-weight:700}.reader-sidebar nav button{font-family:var(--font-body);font-size:.82rem;line-height:1.25;letter-spacing:0}.reader-user strong{font-size:.875rem;line-height:1.3}.reader-header>div>span{font-size:.875rem;line-height:1.5}.reader-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:28px}.reader-stats div{padding:18px;border-radius:14px;background:var(--color-bg-elevated);border:1px solid var(--color-border)}.reader-stats span{display:block;color:var(--color-text-secondary);font-size:.75rem;line-height:1.4;font-weight:550}.reader-stats strong{display:block;color:var(--color-primary);font:700 1.75rem/1.15 var(--font-heading);margin-top:8px}
    @media(max-width:800px){.reader-dashboard{grid-template-columns:1fr;font-size:13px}.reader-sidebar{position:sticky;top:64px;z-index:20;height:auto;padding:10px;border-right:0;border-bottom:1px solid var(--color-border);box-shadow:0 8px 24px rgba(0,0,0,.24)}.reader-user,.reader-home{display:none}.reader-sidebar nav{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.reader-sidebar nav button{width:100%;min-width:0;justify-content:center;flex-direction:column;gap:4px;padding:8px 3px;font-size:11px;line-height:1.15;font-weight:600}.nav-icon{width:25px;height:25px;font-size:13px}.reader-main{padding:18px 12px 28px}.reader-header{align-items:center;margin-bottom:18px}.reader-header h1{font-size:clamp(1.45rem,7vw,1.7rem);line-height:1.2}.reader-header>div>span{font-size:.8rem}.header-badge{display:none}.reader-main>section,.reader-main>form{padding:16px;border-radius:14px}.reader-main h2{font-size:1.12rem}.reader-main p,.reader-main a,.reader-main label,.reader-main input,.reader-main textarea,.reader-main select,.reader-main button{font-size:.82rem}.reader-stats{grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:22px}.reader-stats div{display:block;padding:12px 7px;text-align:center}.reader-stats span{font-size:.68rem;line-height:1.25}.reader-stats strong{margin-top:5px;font-size:1.25rem}}
  `}</style></div></main>;
}
/* eslint-disable @next/next/no-html-link-for-pages */
